@echo build libevent-2.1.8-stable
cd /d %ROOT_DIR%
IF EXIST %MBEDTLS_BUILD_DIR% (RD /S /Q %MBEDTLS_BUILD_DIR%)
MKDIR %MBEDTLS_BUILD_DIR% 
cd /d %MBEDTLS_BUILD_DIR%
cmake -DVISUAL_STUDIO=2017 -DENABLE_ZLIB_SUPPORT=ON -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% -DCMAKE_INSTALL_PREFIX=%BUILD_OUT% -G "NMake Makefiles" %MBEDTLS_SRC%
nmake
nmake install