
@echo build cpr
cd /d %ROOT_DIR%
IF EXIST %CPR_BUILD_DIR% (RD /S /Q %CPR_BUILD_DIR%)
MKDIR %CPR_BUILD_DIR% 
cd /d %CPR_BUILD_DIR%
cmake -DVISUAL_STUDIO=2017 -DCMAKE_USE_OPENSSL=YES -DUSE_SYSTEM_CURL=YES -DBUILD_CPR_TESTS=NO -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=%BUILD_OUT% -G "NMake Makefiles" %CPR_ROOT%
nmake
@echo copy cpr sdk
XCOPY /S /Y %CPR_ROOT%\include\*.h %BUILD_OUT%\include
XCOPY /S /Y %CPR_BUILD_DIR%\lib\*.lib %BUILD_OUT%\lib
