set PATH=%PATH%;%BUILD_OUT%
cd /d %ROOT_DIR%
IF EXIST %NGHTTP2_BUILD_DIR% (RD /S /Q %NGHTTP2_BUILD_DIR%)
MKDIR %NGHTTP2_BUILD_DIR% 
cd /d %NGHTTP2_BUILD_DIR%
cmake -D VISUAL_STUDIO=2017 -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% -DCMAKE_INSTALL_PREFIX=%BUILD_OUT% -G "NMake Makefiles" %NGHTTP2_SRC%
nmake
nmake install
@echo f | XCOPY /Y %BUILD_OUT%\lib\nghttp2.lib %BUILD_OUT%\lib\nghttp2_static.lib